name: PUBLISH FRONTEND BUILD
on:
  push:
    branches:
      - frontend-build-img
jobs:
  buildAndPush:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.TOKEN_GITHUB }}

      - name: Docker login
        run: docker login ${{ secrets.CI_REGISTRY_URL }} -u ${{ secrets.REGISTRY_USER }} -p ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and Tag
        run: |
          docker build -t ${{ secrets.APP_FRONTEND_BUILD }} -f frontend-build-img/Dockerfile .
          docker tag ${{ secrets.APP_FRONTEND_BUILD }} ${{ secrets.CI_REGISTRY_URL }}/${{ secrets.NAMESPACE }}/${{ secrets.APP_FRONTEND_BUILD }}:latest

      - name: Push
        run: docker push ${{ secrets.CI_REGISTRY_URL }}/${{ secrets.NAMESPACE }}/${{ secrets.APP_FRONTEND_BUILD }}:latest
